navigate_to_pose_server:
  ros__parameters:
    navigation_mode: nav2
    cmd_vel_topic: /cmd_vel
    odom_topic: /odom
    named_place_pose_topic: /sim/named_place_poses
    control_rate_hz: 10.0
    linear_speed_mps: 0.35
    angular_speed_rps: 0.8
    yaw_gain: 1.5
    heading_tolerance_rad: 0.2
    named_places_file: /home/jnu/llm_yolo/configs/sim/sim_named_places.yaml
    default_goal_radius_m: 0.5
    default_goal_yaw_rad: 0.0
    action_name: /llm_navigate_to_pose
    nav2_action_name: /navigate_to_pose
    global_frame: map
    nav2_server_wait_sec: 5.0
    speed_scale_slow: 0.6
    speed_scale_normal: 1.0
    speed_scale_fast: 1.25
    person_pause_enabled: true
    person_visible_objects_topic: /perception/visible_objects
    person_object_pose_topic: /perception/object_poses
    person_target_class: person
    person_pause_distance_m: 1.5
    person_pause_trigger_count: 1
    person_pause_clear_count: 2

approach_object_server:
  ros__parameters:
    object_pose_topic: /perception/object_poses
    navigate_action_name: /llm_navigate_to_pose
    odom_topic: /odom
    default_approach_distance_m: 0.5

rotate_in_place_server:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    angular_speed_rps: 0.8
    control_rate_hz: 10.0

scan_scene_server:
  ros__parameters:
    detected_objects_topic: /perception/visible_objects
    default_detected_objects:
      - chair
      - person
    enable_rotate_scan: true
    rotate_scan_num_views: 36
    rotate_scan_step_yaw_rad: 0.1745329252
    rotate_scan_settle_sec: 0.05
    rotate_timeout_sec: 5

perception_node_sim:
  ros__parameters:
    sim_visible_objects_topic: /sim/visible_objects
    normalized_objects_topic: /perception/visible_objects
    object_pose_topic: /perception/object_poses
    camera_image_topic: /camera/color/image_raw
    camera_depth_topic: /camera/depth/image_rect_raw
    camera_info_topic: /camera/camera_info
    object_pose_frame: map
    default_visible_objects:
      - chair
      - person
